<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_Cart
 */
?>
<?php
/** @var \Amasty\Cart\Block\Config  $this */

$hlr = $this->getHelper();
//Visual Options
$backgroundColor        = $hlr->getBackgroundColor();
$headerBackgroundColor  = $hlr->getHeaderBackgroundColor();
$textColor              = $hlr->getTextColor();
$buttonTextColor        = $hlr->getButtonTextColor();
$leftButtonColor        = $hlr->getLeftButtonColor();
$rightButtonColor       = $hlr->getRightButtonColor();
?>

<style>
    #confirmBox,
    .am-related-title > .am-title {
        background-color: <?= $backgroundColor ?>;
    }

    #confirmBox a,
    #confirmBox a:hover,
    #confirmBox a:active {
        color: <?= $headerBackgroundColor ?>;
    }

    #confirmButtons .button {
        color: <?= $buttonTextColor ?>;
    }

    #confirmButtons .am-btn-left {
        background-color: <?= $leftButtonColor ?>;
    }

    #confirmButtons .am-btn-right {
        background-color: <?= $rightButtonColor ?>;
    }

    #confirmButtons,
    #messageBox {
        color: <?= $textColor ?>;
    }

</style>
