<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$param=$block->getToolbarBlock()->getGridVarName();
$gridvar = (int) $this->getRequest()->getParam($param);
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
		
		if($gridvar==2){
			$class="col-md-6 col-sm-6 pd";
			$image = 'category_page_grid_2';
		}elseif($gridvar==4){
			$class="col-md-3 col-sm-6 pd";
			$image = 'category_page_grid_4';
			
		}else{
			$image = 'category_page_grid';	
			$class="col-md-4 col-sm-6 pd";
		}
		
    } else {
        $class = '';
		$viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
		
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?= /* @escapeNotVerified */ $viewMode ?> products-<?= /* @escapeNotVerified */ $viewMode ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
				<?php
					
					$isOutlet = $_product->getIsOutlet();
					
					$newsFromDate = $_product->getData('news_from_date');
					
					$newsToDate  =  $_product->getData('news_to_date');
					
					$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
					$objDate = $objectManager->create('Magento\Framework\Stdlib\DateTime\DateTime');
					$date = $objDate->gmtDate();
					
					if(($newsFromDate < $date && $newsFromDate != NULL) && ($newsToDate > $date || $newsToDate == "")){
						$isNew=1;
					}
					else{
						$isNew=0;
					}
				?>
                <?= /* @escapeNotVerified */ ($iterator++ == 1) ? '<li class="'.$class.' item product product-item">' : '</li><li class="'.$class.' item product product-item">' ?>
				<div class="product-item-info" data-container="product-grid">
				
					<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
					<a href="#"
					   class="action towishlist"
					   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
					   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
					   data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>'
					   data-action="add-to-wishlist"
					   role="button">
						<span><?php /* @escapeNotVerified */ //echo __('Add to Wish List') ?></span>
					</a>
					<?php endif; ?>
				
					<?php if($_product->isAvailable() && isset($isNew) && $isNew==1): ?>
					<div class="sale-tag main-tag"><?php echo __('New');?></div>
					<span class="nav-right-tag2"></span>
					<?php elseif(isset($isNew) && $isNew==1): ?>   
					<div class="outlet2 main-tag"><?php echo __('Coming soon');?>
						<span class="nav-right-tag"></span>
					</div>	
					<div class="sale-tag main-tag"><?php echo __('New');?></div>
					<span class="nav-right-tag2"></span>
					<?php elseif (!$_product->isAvailable()): ?>  							
					<div class="outlet main-tag"><?php echo __('Coming soon');?>
					<span class="nav-right-tag"></span>
					</div>			
					<?php elseif($_product->getFinalPrice() < $_product->getPrice()): ?>
					<?php endif;?>
				
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
                                <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                            </a>
                        </strong>
						
						<?php 
							$getBrand 	= $_product->getResource()->getAttribute('brand');
							$brandValue = $getBrand->getFrontend()->getValue($_product);
						?>
						<strong class="product brand product-item-brandname">
							<a class="product-item-link"
                               href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>">
							<?= /* @escapeNotVerified */ $brandValue ?>
							</a>
						</strong>
						
						<?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?= /* @escapeNotVerified */ $block->getProductPrice($_product) ?>
                        <?= $block->getProductDetailsHtml($_product) ?>

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                            <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                            <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                    class="action tocart primary">
                                                <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                            </button>
                                        </form>
                                    <?php else: ?>
                                        <?php if ($_product->isAvailable()): ?>
                                            <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?= /* @escapeNotVerified */ $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?= /* @escapeNotVerified */ $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */ $_productNameStripped ?>"
                                       class="action more"><?= /* @escapeNotVerified */ __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
				<?= ($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= /* @NoEscape */ $_product->getSku() ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
