<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_Conf
 */
?>
<div class="gallery-placeholder" data-gallery-role="gallery-placeholder">
    <div id="amasty-gallery" data-role="amasty-gallery">
        <div class="gallery-placeholder _block-content-loading" data-gallery-role="gallery-loading">
            <div data-role="loader" class="loading-mask">
                <div class="loader">
                    <img src="<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>"
                         alt="<?= /* @escapeNotVerified */ __('Loading...') ?>">
                </div>
            </div>
        </div>
        <!--Fix for jumping content. Loader must be the same size as gallery.-->
        <script>

            var config = {
                    "width": <?= /* @escapeNotVerified */ $block->getImageAttribute('product_page_image_medium', 'width') ?>,
                    "thumbheight": <?php /* @escapeNotVerified */ echo $block->getImageAttribute('product_page_image_small', 'height')
                    ?: $block->getImageAttribute('product_page_image_small', 'width'); ?>,
                    "navtype": "<?= /* @escapeNotVerified */ $block->getVar("gallery/navtype") ?>",
                    "height": <?= /* @escapeNotVerified */ $block->getImageAttribute('product_page_image_medium', 'height') ?>
                },
                thumbBarHeight = 0,
                loader = document.querySelectorAll('[data-gallery-role="gallery-placeholder"] [data-role="loader"]')[0];

            if (config.navtype === 'horizontal') {
                thumbBarHeight = config.thumbheight;
            }

            loader.style.paddingBottom = ( config.height / config.width * 100) + "%";
        </script>

        <div id="amasty-main-container" data-gallery-role="amasty-main-container"></div>
        <div id="amasty-gallery-container"  data-gallery-role="amasty-gallery-container">
            <div class="amasty-gallery-label"><h2><!-- We can add any label like "More Views" --></h2></div>
            <div id="amasty-gallery-images"  data-gallery-role="amasty-gallery-images"></div>
        </div>
		<?php
			$options = str_replace('"main_image_swipe":false','"main_image_swipe":true',$block->getGalleryOptionJson());
		
			//$options = str_replace('"slidesToShow":3','"slidesToShow":2',$options);
		?>
        <script type="text/x-magento-init">
        {
            "[data-role=amasty-gallery]": {
                "Amasty_Conf/js/amzoomer": {
                    "data": <?= /* @escapeNotVerified */ $block->getGalleryImagesJson() ?>,
                    "options":<?= /* @escapeNotVerified */ $options ?>
                }
            }
        }
        </script>
    </div>
</div>