<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2018 Amasty (https://www.amasty.com)
 * @package Amasty_Checkout
 */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); //instance of\Magento\Framework\App\ObjectManager
$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface'); 
$currentStore = $storeManager->getStore();
$mediaUrl = $currentStore->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
?>
<?php /** @var $block \Magento\Checkout\Block\Onepage\Success */ ?>
<div class="checkout-success">
    <?php if ($block->getOrderId()):?>
        <div class="suceess-container">
	        <div class="success-left">
	        	<div class="success-image">
	        		<img src="<?php echo $mediaUrl.'wysiwyg/Sun-gif.gif'?>" alt="order success">
	        	</div>
	        </div>
	        <div class="success-right">
		        <div class="success-messages">
		            <p><?= __('Your order has been successfully completed! In brief you will receive an email with all the information.') ?></p>
		            <?php if ($block->getCanViewOrder()) :?>
		                <p class="orderno"><?= __('Order number: %1.', sprintf('<a href="%s" class="order-number"><strong>%s</strong></a>', $block->escapeHtml($block->getViewOrderUrl()), $block->escapeHtml($block->getOrderId()))) ?></p>
		            <?php  else :?>
		                <p class="orderno"><?= __('Order number: <span>%1</span>.', $block->escapeHtml($block->getOrderId())) ?></p>
		            <?php endif;?>
		        </div>
		        <div class="contact-info">
					<p class="info-msg"><?= __('For any questions you can contact us via:') ?></p>
					<div class="phone-number"><span class="telephone"></span> <a href="tel:965 59 99 56">965 59 99 56</a></div>
					<div class="email-friday"><span class="email"></span> <a href="mailto:adrian@happyfriday.es">adrian@happyfriday.es</a></div>
				</div>
				<div class="coupen-info">
					<p><?= __('This does not end here') ?></p>
					<p><?= __('We give you a %1 discount on your next purchase with the code:', '<b>10%</b>') ?></p>
					<p><img src="<?php echo $mediaUrl.'wysiwyg/happy.png'?>" alt="happy" /></p>
				</div>
	    	</div>
	    </div>

	    <?= $block->getChildHtml('details') ?>   
    <?php endif;?>
					
		           

    <?= $block->getAdditionalInfoHtml() ?>
    <?= $block->getChildHtml('cms') ?>

    <div class="actions-toolbar">
        <div class="primary">
            <a class="action primary continue" href="<?= $block->getUrl() ?>"><span><?= __('Continue Shopping') ?></span></a>
        </div>
    </div>
</div>

